// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgIf66WKkllcXuKwkvQi84pQRHVLFmfG8',
    appId: '1:1002297328032:web:321d9769505c1a9cc164c5',
    messagingSenderId: '1002297328032',
    projectId: 'fir-111-6ccb6',
    authDomain: 'fir-111-6ccb6.firebaseapp.com',
    databaseURL: 'https://fir-111-6ccb6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-111-6ccb6.firebasestorage.app',
    measurementId: 'G-ME4K09TVX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJx82Ko_pVSvuusxmkZbrpdis3cdGsuz4',
    appId: '1:1002297328032:android:815d8b73e6d5b2f9c164c5',
    messagingSenderId: '1002297328032',
    projectId: 'fir-111-6ccb6',
    databaseURL: 'https://fir-111-6ccb6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-111-6ccb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa3DmJdhWM0YMKx5i4AH1EK-5Q1C1-bZQ',
    appId: '1:1002297328032:ios:a593681ec3f93c1bc164c5',
    messagingSenderId: '1002297328032',
    projectId: 'fir-111-6ccb6',
    databaseURL: 'https://fir-111-6ccb6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-111-6ccb6.firebasestorage.app',
    iosBundleId: 'com.example.pearApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa3DmJdhWM0YMKx5i4AH1EK-5Q1C1-bZQ',
    appId: '1:1002297328032:ios:a593681ec3f93c1bc164c5',
    messagingSenderId: '1002297328032',
    projectId: 'fir-111-6ccb6',
    databaseURL: 'https://fir-111-6ccb6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-111-6ccb6.firebasestorage.app',
    iosBundleId: 'com.example.pearApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgIf66WKkllcXuKwkvQi84pQRHVLFmfG8',
    appId: '1:1002297328032:web:6b3fc05497455e0cc164c5',
    messagingSenderId: '1002297328032',
    projectId: 'fir-111-6ccb6',
    authDomain: 'fir-111-6ccb6.firebaseapp.com',
    databaseURL: 'https://fir-111-6ccb6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-111-6ccb6.firebasestorage.app',
    measurementId: 'G-JKLP6MLGL4',
  );
}
